# Configuration for a basic environment with one agent and obstacles
num_rays: 30
goal_threshold: 0.02

# Boundary configuration
boundary:
  type: polygon
  vertices:
    - { x: 0.1, y: 0.1 }
    - { x: 0.9, y: 0.1 }
    - { x: 0.9, y: 0.9 }
    - { x: 0.1, y: 0.9 }

# Agents configuration
agents:
  - start_pos:
      x: 0.5
      y: 0.25
    goal_pos:
      x: 0.5
      y: 0.85
    radius: 0.02
    max_speed: 0.2
    fov_degrees: 90 
    spawn_time: 0.0
    max_range: 0.3

# Obstacles configuration
obstacles:
  # Rectangular obstacle
  - shape:
      type: rectangle
      center:
        x: 0.5
        y: 0.5
      width: 0.25
      height: 0.1

max_time: 1000
