
# Configuration for a basic environment with one agent and obstacles

# Agents configuration
agents:
  - start_pos:
      x: 0.5
      y: 0.0
    goal_pos:
      x: 0.5
      y: 1.0
    max_speed: 0.5
    preferred_speed: 0.2
    spawn_time: 0.0

# Obstacles configuration
obstacles:
  # Rectangular obstacle
  - type: rectangle
    center:
      x: 0.75
      y: 0.5
    width: 0.2
    height: 0.2

  # Line obstacles on the two sides
  - type: line
    start:
      x: 0.1
      y: 0.0
    end:
      x: 0.1
      y: 1.0
  - type: line
    start:
      x: 0.9
      y: 0.0
    end:
      x: 0.9
      y: 1.0
max_time: 100

