# Configuration for a basic environment with one agent and obstacles
num_rays: 60
goal_threshold: 0.02
num_agents_per_group: 10


# Boundary configuration
boundary:
  type: polygon
  vertices:
    - { x: 0.1, y: 0.1 }
    - { x: 0.9, y: 0.1 }
    - { x: 0.9, y: 0.9 }
    - { x: 0.1, y: 0.9 }

# Agents configuration
agents:
  - start_pos:
      center:
        x: 0.5
        y: 0.25
      width: 0.6
      height: 0.02
    goal_pos:
      center:
        x: 0.5
        y: 0.85
      width: 0.5
      height: 0.02
    radius: 0.012
    max_speed: 0.2
    fov_degrees: 360 
    spawn_time: 0.0
    max_range: 0.5

# Obstacles configuration
obstacles:
  # Rectangular obstacle
  - shape:
      type: rectangle
      center:
        x: 0.65
        y: 0.5
      width: 0.25
      height: 0.1
    schedule:
      speed: 0.1
      direction:
        x: -1
        y: 0
      angular_speed: 10
      boundary_x_min: 0.2
      boundary_x_max: 0.8

  - shape:
      type: rectangle
      center:
        x: 0.25
        y: 0.75
      width: 0.15
      height: 0.1
    schedule:
      speed: 0.1
      direction:
        x: 1
        y: 0
      angular_speed: 20
      boundary_x_min: 0.2
      boundary_x_max: 0.8

  - shape:
      type: rectangle
      center:
        x: 0.5
        y: 0.6
      width: 0.02
      height: 0.2
    schedule:
      angular_speed: 30  # Degrees per second
max_time: 1000
